### ISSUE TITLE
Memory leak when exiting from cmd opt parsing

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#239]
For command line options such as ``--gitinfo`` and ``--version``, the code is immediately exited from without freeing _some_ already allocated memory via ``FreeNames()`` or individually with ``free()``. The memory allocated is for the input and output filename lists.

``FreeNames()`` should check fro ``NULL`` before freeing.

This really shouldn't be explicit to ``FreeNames`` and should instead use ``PtrRegister`` srtuct to facilitate in this.

### Update:
Going to use ``PtrRegister`` instead of ``FreeNames()``. ``FreeNames()`` requires ``NULL`` checking and I can't be bothered to change all of these static funcs. Becuase of this, this issue is dependent on #236 

### Update
This is dependent on:
- [x] #236 Move PtrRegister from hstio/ to lib/ 
- [x] #249 CloseTrlBuf(void) -> CloseTrlBuf(struct TrlBuf * ptr)
- [x] #250 Move PtrRegister to lib/hstcal_memory.c and include/hstcal_memory.h
- [ ] ~~#246 Add PtrRegister::updatePtr(PtrRegister * reg, void * oldPtr, void * newPtr)~~
