### ISSUE TITLE
Add STIS tasks to HSTCAL to be used from stistools

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#262]
- [ ] Add IntTag functionality to STIS #263
 - [ ] Add ovac2air functionality to STIS #265
 - [ ] Add tastis functionality to STIS #266

**Comment by stscicrawford** [comment]
Closing as these functions will not be implemented in HSTCAL
