### ISSUE TITLE
Create new regression tests for CALACS for the bias shift correction for WFC subarrays

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/hstcal#332]
Regression tests should be created which invoke the bias shift correction code for the new supported subarrays, including polarization and ramp data.  A regression test should also be created where the subarray data does **_not_** satisfy all of the criteria for the bias shift correction such that the "original" solution is applied.

- [ ] ⚠️ Jenna's test data from https://github.com/spacetelescope/hstcal/pull/685 (ON HOLD because #329 has been re-opened)
  - jd2j15iyq
  - jd2j16jaq
  - jd2j17jrq
  - jd2j18jzq
  - jd2j19l3q
  - jd2j20lgq
  - jd2j21m7q
  - jd2j22mqq
  - jfch01f4q
  - jfch01flq
- [x] polarization/ramp data #688
- [x] exception logic route that takes data back to pre-SM4 fallback #688
